language: swift
osx_image: xcode9.4
env:
  - DESTINATION="OS=11.4,name=iPhone X" SCHEME="Tisander" SDK=iphonesimulator11.4

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- cd Tisander

script:
- xcodebuild clean build -project Tisander/Tisander.xcproject -scheme "$SCHEME" -sdk "$SDK"
- xcodebuild test -project Tisander/Tisander.xcproject -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" | xcpretty -c
